modLoader="lowcodefml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="icon.png" #optional
credits="" #optional
authors="${mod_authors}" #optional
description='''${mod_description}
'''

