modLoader="lowcodefml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="icon.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

